### ISSUE TITLE
Failed to generate file due to missing dependencies in MI v4.2.0.127

### ISSUE THREAD

**Issue by PasinduGunarathne** [wso2/product-micro-integrator#4202]
### Description

Unable to generate Excel files due to issues in dependencies in MI v4.2.0.127 u2 level. Further this behavior will occur after updating the u2 level from 120 to 121.

### Steps to reproduce

1. Implement a custom mediator that generates an Excel worksheet
2. Update the MI server to the MI v4.2.0.127
3. Invoke the service

### Expected behavior

- Should be able to create an XSL sheet with content 

### Current behavior

- Will throw the below error log

```
[2025-05-29 17:15:30,748] ERROR {NativeWorkerPool} - Uncaught exception java.lang.NoClassDefFoundError: org/apache/commons/io/Charsets
	at org.apache.commons.compress.archivers.zip.ZipEncodingHelper.getZipEncoding(ZipEncodingHelper.java:50)
	at org.apache.commons.compress.archivers.zip.ZipEncodingHelper.<clinit>(ZipEncodingHelper.java:36)
	at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.<init>(ZipArchiveOutputStream.java:338)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:538)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1531)
	at org.apache.poi.ooxml.POIXMLDocument.write(POIXMLDocument.java:227)
	at org.apache.synapse.mediators.ext.ClassMediator.updateInstancePropertiesAndMediate(ClassMediator.java:182)
	at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:95)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:126)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:74)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:214)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:126)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:74)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.api.Resource.process(Resource.java:342)
	at org.apache.synapse.api.API.process(API.java:484)
	at org.apache.synapse.api.AbstractApiHandler.apiProcess(AbstractApiHandler.java:94)
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:72)
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:90)
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:76)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:352)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:101)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:399)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:458)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:206)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.Charsets cannot be found by commons-compress_1.27.1.wso2v1
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	... 35 more
```

### Version

v4.2.0
